os: linux
dist: xenial
language: node_js
node_js:
  - "node"
branches:
  only:
    - main
    - develop
jobs:
  include:
    - stage: "test"
      name: "General tests"
      script: npm run test:coverage && coveralls < coverage/lcov.info
    - stage: "Build"
      name: "Typescript declaration build"
      script: npm run build:declaration
    - script: npm run build:docs
      name: "Docs build"
env:
  global:
    - COVERALLS_PARALLEL=true
notifications:
  webhooks: https://coveralls.io/webhook
