os: linux
dist: xenial
language: node_js
node_js:
  - "node"
branches:
  only:
    - master
    - develop
script:
  - npm run pretest
  - npm run lint
  - npm run test:coveralls
  - npm run docs:build
deploy:
  provider: pages:git
  edge: true
  token: $GITHUB_TOKEN
  local_dir: docs/.vuepress/dist
  keep_history: false
  on:
    branch: master
env:
  global:
    - COVERALLS_PARALLEL=true
notifications:
  webhooks: https://coveralls.io/webhook
